version: '3'
services:
  # php
  php:
    # image: php:7.2-apache
    build:
      context: .
      dockerfile: dockerfile-php
    container_name: web_php-apache
    ports:
      - 80:80
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./html/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - network01

  # MySQL
  mysql:
    # image: mysql:5.7
    build:
      context: .
      dockerfile: dockerfile-mysql
    platform: linux/x86_64
    container_name: web_mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/mysql.cnf
      - ./config/profile:/etc/profile
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db
      - MYSQL_HOST=mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - network01

networks:
  network01:
