version: '3'
services:
  # php
  php:
    image: php:7.2-apache
    container_name: web_php-apache
    ports:
      - 80:80
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./html/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: web_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db
    restart: always
